/** path of the application use for router config*/
export const paths = {
  Landing: "/",
  about: "/about",
  contact: "/contact",
  gallery: "/gallery",
  // donation: "/donation",
  ourpartner: "/ourpartner",
  helpcentre: "/helpcentre",
  programdetail: "/Programdetail/:programId",
  blogdetails: "/blogdetails",
  login: "/login",
  partnerdetail: "/Partnerdetail/:partnerId",
  signup: "/signup",
  forgotpassword: "/forgotpassword",
  changepassword: "/changepassword",
  volunteer: "/volunteer",
  program: "/program",
  activeCode: "/forgot-password/active-code",
  resetPassword: "/forgot-password/reset-password",
  resetSuccess: "/forgot-password/success",
  payment: "/payment",
};
