import {
  PayPalScriptProvider,
  BraintreePayPalButtons,
} from "@paypal/react-paypal-js";

export default function PayPal() {
  return (
    <PayPalScriptProvider
      options={{
        clientId: "test",
        dataClientToken:
          "<the data-client-token value generated by your server-side code>",
      }}
    >
      <BraintreePayPalButtons
        createOrder={(data: any, actions: any) => {
          return actions.braintree.createPayment({
            flow: "checkout",
            amount: "10.0",
            currency: "USD",
            intent: "capture",
          });
        }}
        onApprove={(data: any, actions: any) => {
          return actions.braintree
            .tokenizePayment(data)
            .then((payload: any) => {
              // call server-side endpoint to finish the sale
            });
        }}
      />
    </PayPalScriptProvider>
  );
}
